# Generated by Django 4.2.24 on 2025-09-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_guess', models.CharField(max_length=50)),
                ('guessed_letters', models.CharField(max_length=26)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
                ('status', models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('In-Progress', 'In-Progress')], default='In-Progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
