# Generated by Django 4.2.24 on 2025-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guessed_letters',
            field=models.CharField(default='', max_length=26),
        ),
    ]
