# Generated by Django 4.2.24 on 2025-09-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_alter_game_guessed_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('InProgress', 'InProgress')], default='InProgress', max_length=20),
        ),
    ]
